### ISSUE TITLE
When debugger is vscode, exception at importer.py line 141

### ISSUE THREAD

**Issue by cunnane** [cunnane/xloil#117]
When setting `debugger = "vscode"` instead of `debugger = ""`, I still encounter the following error:
```[2024-09-18 09:37:38.888] [logger] [error] [Main.cpp:418] xloil_python_init failed: KeyError: KeyError: ''
Traceback (most recent call last):
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\debug.py", line 166, in use_debugger
    debugpy_listen(**kwargs)
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\debug.py", line 56, in debugpy_listen
    addin = xloil.source_addin()
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\excel\.venv\Lib\site-packages\xloil\importer.py", line 141, in source_addin
    else xloil_core.xloil_addins[addin_path]
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: ''
```

_Originally posted by @gnyuan in https://github.com/cunnane/xloil/issues/114#issuecomment-2357320029_

**Comment by andyvandy** [comment]
In this function do we need to call `import debugpy.server.api` or does that get imported elsewhere before we need it? 

https://github.com/cunnane/xloil/blob/37517ee8417e8bf4b816d0a3db9f9d45f2cb46d2/libs/xlOil_Python/Package/xloil/debug.py#L91-L97

Maybe not directly applicable and I don't quite see how any nearby changes would've triggered it. Took a quick look at this  issue when I saw it mentioned.
