### ISSUE TITLE
Cannot start multiple instances of Excel

### ISSUE THREAD

**Issue by airguru** [cunnane/xloil#27]
When attempting to launch a second instance of Excel, the second instance crashes. The crash happens even before xlOil ribbon tab is displayed, and before even a blank spreadsheet is loaded. The problem disappears when I disable the xloil by moving the xll file out of xlstart.

In the event viewer the `python310.DLL` is named as a culprit. There are some error logs produced by the system, but they mostly only contain OS / program info, I haven't found any specific error message related to the dll. I am attaching one of the logs as an example: 
[Report.txt](https://github.com/cunnane/xloil/files/10481441/Report.txt)

Office 2010, Python 3.10.9, xloil 0.16.4

**Comment by cunnane** [comment]
I've not been able to replicate this, but I have made a change in xlOil 0.17 which avoids log file collision when two instances of Excel are open (although I can't see how this would cause a crash)

**Comment by airguru** [comment]
It seems that this has been the issue! On 0.17.3 I no longer observe it!

However, when debugging is enabled, the two ribbons fight over the socket and the second one loses and crashes. 
```
[2023-02-16 16:04:03.753] [logger] [error] [Main.cpp:392] xloil_python_init failed: RuntimeError: RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
Traceback (most recent call last):
  File "C:\xloil_env\lib\site-packages\xloil\debug.py", line 163, in use_debugger
    debugpy_listen(**kwargs)
  File "C:\xloil_env\lib\site-packages\xloil\debug.py", line 60, in debugpy_listen
    connection = debugpy.listen(port)
  File "C:\xloil_env\lib\site-packages\debugpy\public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\xloil_env\lib\site-packages\debugpy\server\api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "C:\xloil_env\lib\site-packages\debugpy\server\api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "C:\xloil_env\lib\site-packages\debugpy\server\api.py", line 262, in listen
    raise RuntimeError(str(endpoints["error"]))
RuntimeError: Can't listen for client connections: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

I guess this is survivable while outputting some console error message?

**Comment by cunnane** [comment]
In 0.17.4 I make a check on the port availability and find a new one if required.  The available port number should show in the ribbon but it won't be saved to the xlOil.ini file
