### ISSUE TITLE
COM object

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#54]
I am trying to move my VBA to xloil using the com object

`xlo.app().Range("A4", "B5").Value = ((1, 2), (3, 4))` 

I have this error
ModuleNotFoundError: No module named "pythoncom"

I manually installed `pywin32` library, which includes `pythoncom `in my venv but again no luck

[2023-08-19 18:50:50.335] [logger] [error] [PyFunctionRegister.cpp:140] py_change_font: AttributeError: AttributeError: module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'CLSIDToClassMap'
Traceback (most recent call last):
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 455, in EnsureModule
    module = GetModuleForTypelib(typelibCLSID, lcid, major, minor)
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 283, in GetModuleForTypelib
    mod = _GetModule(modName)
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 726, in _GetModule
    mod = __import__(mod_name)
ModuleNotFoundError: No module named 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ShieldTrade\Ave\Oil\Oil_1.py", line 51, in py_change_font
    xlo.app().Range("A4", "B5").Value = ((1, 2), (3, 4))
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 471, in EnsureModule
    module = GetModuleForTypelib(
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 287, in GetModuleForTypelib
    AddModuleToCache(typelibCLSID, lcid, major, minor)
  File "C:\shieldtrade\ave\venv\lib\site-packages\win32com\client\gencache.py", line 661, in AddModuleToCache
    SetTypelibForAllClsids(mod.CLSIDToClassMap)
AttributeError: module 'win32com.gen_py.00020813-0000-0000-C000-000000000046x0x1x9' has no attribute 'CLSIDToClassMap'

**Comment by cunnane** [comment]
I've added what I'm pretty sure is the answer to the [FAQ](https://xloil.readthedocs.io/en/stable/xlOil_Python/FAQ.html)

**Comment by ShieldTrade** [comment]
Command prompt.

```
c:\ShieldTrade\Ave\venv\Scripts>python clear_comtypes_cache.py -y

Removed directory "c:\ShieldTrade\Ave\venv\lib\site-packages\comtypes\gen"
Removed directory "C:\Users\lucio\AppData\Roaming\Python\Python39\comtypes_cache"
```

Restarted excel but I have the same error.

**Comment by cunnane** [comment]
You're clearing the *comtypes* (another com support module) cache, not the *win32com* one.  Try [this answer](https://xloil.readthedocs.io/en/stable/xlOil_Python/FAQ.html#win32com-pythoncom-some-clsid-has-no-attribute-clsidtoclassmap)

**Comment by ShieldTrade** [comment]
It works. Thankyou
