### ISSUE TITLE
Type Conversion: error when trying to use return type xloil.array

### ISSUE THREAD

**Issue by ShieldTrade** [cunnane/xloil#57]
```
@ xlo.func()
def py_test_array() -> xlo.Array:
    arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]])
    return arr
```
When uploading xloil I have this error.  Same error if I use `numpy.ndarray.
`
```
[2023-08-26 19:39:39.504] [logger] [error] [logging.py:25] Failed determing spec for 'py_test_array': Traceback (most recent call last):
  File "C:\shieldtrade\ave\venv\lib\site-packages\xloil\register.py", line 423, in decorate
    spec.return_converter = find_return_converter(return_type)
  File "C:\shieldtrade\ave\venv\lib\site-packages\xloil\register.py", line 131, in find_return_converter
    ret_con = Return_object()
NameError: name 'Return_object' is not defined
```

**Comment by cunnane** [comment]
This is fixed in 0.17.13 which was released this week
